-- Crear usuario para la aplicacion
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER gadicc_app IDENTIFIED BY gadicc2026 DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SEQUENCE TO gadicc_app;
GRANT CREATE SESSION TO gadicc_app;

-- Conectar como el nuevo usuario
CONNECT gadicc_app/gadicc2026@localhost:1521/GADICC_PROJECT

-- TABLA PERSONA
CREATE TABLE PERSONA (
    CEDULARUCPERSONA        NVARCHAR2(14)   NOT NULL,
    PRIMERNOMBREPERSONA     NVARCHAR2(100),
    SEGUNDONOMBREPERSONA    NVARCHAR2(100),
    PRIMERAPELLIDOPERSONA   NVARCHAR2(100),
    SEGUNDOAPELLIDOPERSONA  NVARCHAR2(100),
    DIRECCIONPERSONA        NVARCHAR2(300),
    MOVIL1PERSONA           NVARCHAR2(20),
    EMAIL1PERSONA           NVARCHAR2(100),
    ACTIVO                  NUMBER(1) DEFAULT 1,
    CONSTRAINT PK_PERSONA PRIMARY KEY (CEDULARUCPERSONA)
);

-- TABLA EMPLEADO
CREATE TABLE EMPLEADO (
    CEDULARUCPERSONA    NVARCHAR2(14)   NOT NULL,
    NOTASEMPLEADO       VARCHAR2(250),
    IDDEPARTAMENTO      NUMBER,
    CARGOEMPLEADO       VARCHAR2(100),
    IDTIPOFUNCIONARIO   NUMBER,
    EMPLEADOACTIVO      NUMBER DEFAULT 1,
    CODIGOSECTORIAL     VARCHAR2(50),
    TITULOPROFESIONAL   VARCHAR2(150),
    CONSTRAINT PK_EMPLEADO PRIMARY KEY (CEDULARUCPERSONA),
    CONSTRAINT FK_EMPLEADO_PERSONA FOREIGN KEY (CEDULARUCPERSONA)
        REFERENCES PERSONA(CEDULARUCPERSONA)
);

-- TABLA EMPLEADO_QR
CREATE TABLE EMPLEADO_QR (
    CEDULARUCPERSONA    NVARCHAR2(14)   NOT NULL,
    TOKENQR             NVARCHAR2(32)   NOT NULL,
    CODIGOQR            CLOB,
    FECHAGENERACION     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ACTIVO              NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_EMPLEADO_QR PRIMARY KEY (CEDULARUCPERSONA),
    CONSTRAINT FK_EMPQR_EMPLEADO FOREIGN KEY (CEDULARUCPERSONA)
        REFERENCES EMPLEADO(CEDULARUCPERSONA),
    CONSTRAINT UQ_EMPLEADO_QR_TOKEN UNIQUE (TOKENQR)
);

CREATE INDEX IDX_EMPQR_TOKEN ON EMPLEADO_QR(TOKENQR);

-- TABLA CALIFICACIONES
CREATE TABLE CALIFICACIONES (
    IDCALIFICACION      NUMBER          NOT NULL,
    CEDULARUCPERSONA    NVARCHAR2(14)   NOT NULL,
    VALOR               NUMBER(1)       NOT NULL,
    COMENTARIOS         NVARCHAR2(500),
    FECHAHORA           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    IPCLIENTE           VARCHAR2(45),
    DEVICEFINGERPRINT   VARCHAR2(16),
    USERAGENT           VARCHAR2(500),
    FECHACLIENTE        TIMESTAMP,
    CONSTRAINT PK_CALIFICACIONES PRIMARY KEY (IDCALIFICACION),
    CONSTRAINT FK_CALIF_EMPLEADO FOREIGN KEY (CEDULARUCPERSONA)
        REFERENCES EMPLEADO(CEDULARUCPERSONA),
    CONSTRAINT CK_CALIF_VALOR CHECK (VALOR IN (1, 2, 3, 4))
);

CREATE SEQUENCE SEQ_CALIFICACIONES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_CALIFICACIONES_ID
BEFORE INSERT ON CALIFICACIONES
FOR EACH ROW
BEGIN
    IF :NEW.IDCALIFICACION IS NULL THEN
        :NEW.IDCALIFICACION := SEQ_CALIFICACIONES.NEXTVAL;
    END IF;
END;
/

CREATE INDEX IDX_CALIF_EMPLEADO ON CALIFICACIONES(CEDULARUCPERSONA);
CREATE INDEX IDX_CALIF_FECHA ON CALIFICACIONES(FECHAHORA DESC);

-- TABLA USUARIOS_ADMIN
CREATE TABLE USUARIOS_ADMIN (
    IDUSUARIO       NUMBER          NOT NULL,
    NOMBREUSUARIO   NVARCHAR2(50)   NOT NULL,
    PASSWORDHASH    NVARCHAR2(200)  NOT NULL,
    FECHACREACION   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_USUARIOS_ADMIN PRIMARY KEY (IDUSUARIO),
    CONSTRAINT UQ_USUARIOS_NOMBRE UNIQUE (NOMBREUSUARIO)
);

CREATE SEQUENCE SEQ_USUARIOS_ADMIN START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_USUARIOS_ADMIN_ID
BEFORE INSERT ON USUARIOS_ADMIN
FOR EACH ROW
BEGIN
    IF :NEW.IDUSUARIO IS NULL THEN
        :NEW.IDUSUARIO := SEQ_USUARIOS_ADMIN.NEXTVAL;
    END IF;
END;
/

-- DATOS INICIALES
-- Usuario admin (password: Admin123!)
INSERT INTO USUARIOS_ADMIN (IDUSUARIO, NOMBREUSUARIO, PASSWORDHASH, FECHACREACION)
VALUES (SEQ_USUARIOS_ADMIN.NEXTVAL, 'admin', '$2a$12$boDZnBuVosLhLIeyxwk2ZOULaEamHoc9U7LFQ530D36bR9gwor0u6', SYSTIMESTAMP);

-- Empleados de prueba
INSERT INTO PERSONA (CEDULARUCPERSONA, PRIMERNOMBREPERSONA, PRIMERAPELLIDOPERSONA, DIRECCIONPERSONA, ACTIVO)
VALUES ('0102030405', 'Carlos', 'Gonzalez', 'Av. Principal 123', 1);

INSERT INTO PERSONA (CEDULARUCPERSONA, PRIMERNOMBREPERSONA, PRIMERAPELLIDOPERSONA, DIRECCIONPERSONA, ACTIVO)
VALUES ('0605040302', 'Mateo', 'Ortiz', 'Calle Bolivar 456', 1);

INSERT INTO EMPLEADO (CEDULARUCPERSONA, CARGOEMPLEADO, EMPLEADOACTIVO, CODIGOSECTORIAL)
VALUES ('0102030405', 'Atencion al Ciudadano', 1, 'SEC-001');

INSERT INTO EMPLEADO (CEDULARUCPERSONA, CARGOEMPLEADO, EMPLEADOACTIVO, CODIGOSECTORIAL)
VALUES ('0605040302', 'Ventanilla Unica', 1, 'SEC-002');

COMMIT;

-- Vista de consulta
CREATE OR REPLACE VIEW V_CALIFICACIONES_EMPLEADO AS
SELECT
    c.IDCALIFICACION,
    c.CEDULARUCPERSONA,
    p.PRIMERNOMBREPERSONA || ' ' || p.PRIMERAPELLIDOPERSONA AS NOMBRE_COMPLETO,
    e.CARGOEMPLEADO,
    CASE c.VALOR
        WHEN 1 THEN 'Excelente'
        WHEN 2 THEN 'Buena'
        WHEN 3 THEN 'Regular'
        WHEN 4 THEN 'Mala'
    END AS VALOR_TEXTO,
    c.VALOR,
    c.COMENTARIOS,
    c.FECHAHORA,
    c.IPCLIENTE,
    c.DEVICEFINGERPRINT
FROM CALIFICACIONES c
INNER JOIN EMPLEADO e ON c.CEDULARUCPERSONA = e.CEDULARUCPERSONA
INNER JOIN PERSONA p ON e.CEDULARUCPERSONA = p.CEDULARUCPERSONA;

EXIT;
